[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
remappings = ["@openzeppelin-upgrade/=lib/openzeppelin-contracts-upgradeable", "@openzeppelin/=lib/openzeppelin-contracts", "@chainlink/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config